# Site
repository: DenisaDzulova/modern-resume-theme
favicon: images/favicon.ico

# Personal info 
name: Denisa Džulová
title: Postdoctoral researcher, Switzerland
email: Denisa.Dzulova@irovision.ch
# website: https://dylanlawlessblog.wordpress.com

# Social links
# twitter_username: meddlaw
# github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: lawless.ch
# linkedin_username: dylan-lawless-human-genomics
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0001-8496-3725

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
  
# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I have obtained a PhD in Ophthalmic Genetics at Section of Ophthalmology and Neuroscience at University of Leeds, Leeds, United Kingdom in 2018. 
  The focus of my PhD was using NGS technology to identify the genetic bases of a blinding idiopathic and non-hereditary retinal vasculopathy called Coats disease from aged FFPE enucleated eyes. 
  I have implemented many of techniques and skills acquired throughout my PhD into my current Postdoctoral position which focuses on stem cell research of retinal vascular diseases. 
  I have developed a strong interest in genomics and stem cell research, and I’ve learnt what this entails in the laboratory setting.
  Now I am interested in applying my expertise of genetics, NGS and stem cells into clinical product development which allows me to put the research into practice. 

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

awards_title: Awards

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#  Other skills
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [url link](https://www.youtube.com/)


# Footer
footer_show_references: true

# Build settings
remote_theme: DenisaDzulova/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

future: true
